Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,7 +28,7 @@ jobs:
     - name: Run Flake8
       continue-on-error: true
       run: |
-        flake8 ./game --format=html --htmldir=flake8_report
+        flake8 ./game --format=html --htmldir=flake8_report || echo "Flake8 found issues"
 
     - name: Upload test reports
       uses: actions/upload-artifact@v2
@@ -41,3 +41,9 @@ jobs:
       with:
         name: lint-report
         path: flake8_report/
+
+    - name: Display logs
+      if: failure()
+      run: |
+        echo "Linting errors or warnings:"
+        cat flake8_report/*.html || true
